version: "3.3"

services:
  todo_db:
    container_name: todo_db
    image: postgres:latest
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=todo
      - POSTGRES_USER=todo
    ports:
      - 5536:5432
