name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cp contrib/env-sample .env
        python -m pip install --upgrade pip
        pip install -q pipenv
        export PIPENV_VENV_IN_PROJECT=1
        pipenv sync --dev
    - name: Run Tests
      run: |
        pipenv run python manage.py test
